// Every pointwise op kernel against its CPU reference (spec section 15, milestone 5).
//
// Seven of the nine kernels had never been executed before this test existed: they compiled, and the
// compiler used their registry entries, but nothing had ever read their output. That is exactly the
// gap a reference comparison closes.
//
// The inputs are uploaded through the staging ring rather than generated by another kernel, because
// generated inputs would only prove that two kernels agree with each other. The nodes themselves are
// built through the graph builders, so the parameter packing the builders do is under test too: a
// kernel reading word 2 while the builder writes word 3 would show up here.

#include "gpu_support.hpp"

#include <engine/application.hpp>
#include <engine/engine.hpp>
#include <engine/memory/general.hpp>
#include <engine/terrain/graph.hpp>
#include <engine/terrain/kernels.hpp>
#include <engine/terrain/mapping.hpp>

#include <algorithm>
#include <cmath>
#include <cstring>
#include <memory_resource>
#include <vector>

using namespace engine;
using namespace engine::vulkan;
using namespace engine::terrain;

namespace {

/// Small enough to keep the test quick, large enough to cross many workgroups.
constexpr SectionExtent kExtent{.x = 24, .y = 1, .z = 24};
constexpr SectionExtent kExtent3{.x = 8, .y = 8, .z = 8};
constexpr u32_t         kHalo = 0;

/// GLSL and C++ group their arithmetic differently in places, and `pow`, `normalize` and `length`
/// are allowed to differ by a few ULP, so agreement to a few f32 epsilons is the bar.
constexpr f64_t kTolerance = 2e-5;

/// Deterministic pseudo-random values in [-1, 1]. A fixed sequence rather than a rand() so a failure
/// is reproducible and the CPU side sees exactly what the GPU did.
[[nodiscard]] f32_t SampleValue(u32_t stream, u64_t index) {
    u32_t h = static_cast<u32_t>(index) * 0x9E3779B9u + stream * 0x85EBCA6Bu;
    h ^= h >> 16;
    h *= 0x7FEB352Du;
    h ^= h >> 15;
    h *= 0x846CA68Bu;
    h ^= h >> 16;
    return static_cast<f32_t>(static_cast<f64_t>(h >> 8) / 8388608.0 - 1.0);
}

/// One input of the op under test: its own slot and the host copy the reference reads.
struct Input {
    Mapping                 mapping;
    SectionSlot             slot;
    std::pmr::vector<f32_t> host{&memory::General().Resource()};
};

/// Runs one node on the GPU and compares every sample against `EvalPointwise`.
class OpChecker {
public:
    OpChecker(Context& context, const Graph& graph) : m_context(context), m_graph(graph) {}

    ~OpChecker() { ReleaseAll(); }

    ENGINE_NO_COPY(OpChecker);
    ENGINE_NO_MOVE(OpChecker);

    /// `skipNearZeroInput` is the index of an input that must not be near zero, or -1. Division is
    /// the only op that needs it, and skipping is honest: the two sides agree on the special case of
    /// an exactly zero divisor, but a divisor of 1e-7 amplifies a one-ULP input difference without
    /// saying anything about the kernel.
    [[nodiscard]] b8_t Check(u32_t nodeIndex, const char* label, i32_t skipNearZeroInput = -1) {
        const Graph::Node& node   = m_graph.NodeAt(nodeIndex);
        const Domain       domain = node.channels[0].domain;
        const SectionExtent extent = domain == Domain::R3 ? kExtent3 : kExtent;
        const u64_t         samples = SampleCount(node.channels[0], extent, kHalo);

        ReleaseAll();

        // Inputs, filled with a distinct pseudo-random stream each so a swapped operand shows up.
        for (u8_t i = 0; i < node.inputCount; ++i) {
            if (!AddInput(node.inputs[i].mapping, extent, i)) {
                return false;
            }
        }

        const Mapping outputMapping = node.channels[0];
        const u64_t   outputBytes   = ValueSize(outputMapping, extent, kHalo);
        Result<SectionSlot> outputSlot =
            m_context.Sections().Acquire(ClassOf(outputMapping, extent, kHalo), outputBytes);
        if (!outputSlot) {
            std::printf("FAIL %s: %s\n", label, outputSlot.error().Format().data());
            return false;
        }
        m_outputSlot = *outputSlot;

        const OpInfo&        info = OpInfoOf(node.kind);
        SpecializationValues specialization =
            WorkgroupSpecialization(static_cast<u32_t>(domain));
        for (u8_t field = 0; field < info.specFieldCount; ++field) {
            specialization.Add((node.variant >> (field * kVariantFieldBits))
                               & kVariantFieldMask);
        }
        Result<ComputePipeline> pipeline = ComputePipeline::Create(
            m_context.Device(), info.shader, specialization, m_context.Pipelines().Handle());
        if (!pipeline) {
            std::printf("FAIL %s: %s\n", label, pipeline.error().Format().data());
            return false;
        }

        KernelPushConstants constants{};
        constants.origin      = {11, domain == Domain::R3 ? 5 : 0, -7};
        constants.extent      = {extent.x, extent.y, extent.z};
        constants.halo        = kHalo;
        constants.SetDomain(static_cast<u32_t>(domain));
        constants.SetChannelMask(1);
        constants.seed        = 0;
        constants.params      = node.params;
        for (u8_t i = 0; i < node.inputCount; ++i) {
            constants.inputs[i] = m_inputs[i].slot.address;
        }
        constants.outputs[0] = m_outputSlot.address;

        Result<test::Readback> readback =
            test::RunKernel(m_context, *pipeline, m_outputSlot, constants, outputBytes);
        if (!readback) {
            std::printf("FAIL %s: %s\n", label, readback.error().Format().data());
            return false;
        }

        const u8_t outComponents = outputMapping.components;
        u64_t      mismatches    = 0;
        u64_t      skipped       = 0;
        f64_t      worst         = 0.0;
        f64_t      scale         = 1e-6;

        for (u64_t sample = 0; sample < samples; ++sample) {
            std::array<std::array<f32_t, kMaxComponents>, kMaxNodeInputs> inputs{};
            std::array<u8_t, kMaxNodeInputs>                             counts{};
            b8_t                                                        skip = false;
            for (u8_t i = 0; i < node.inputCount; ++i) {
                counts[i] = m_inputs[i].mapping.components;
                for (u8_t c = 0; c < counts[i]; ++c) {
                    inputs[i][c] = m_inputs[i].host[sample * counts[i] + c];
                }
                if (static_cast<i32_t>(i) == skipNearZeroInput
                    && std::fabs(static_cast<f64_t>(inputs[i][0])) < 1e-3) {
                    skip = true;
                }
            }
            if (skip) {
                ++skipped;
                continue;
            }

            std::array<f32_t, kMaxComponents> expected{};
            if (!EvalPointwise(node, inputs, counts, expected)) {
                std::printf("FAIL %s: the op has no CPU reference\n", label);
                return false;
            }
            for (u8_t c = 0; c < outComponents; ++c) {
                const f64_t reference = expected[c];
                const f64_t actual    = readback->data[sample * outComponents + c];
                scale                 = std::max(scale, std::fabs(reference));
                const f64_t error     = std::fabs(actual - reference);
                if (error > worst) {
                    worst = error;
                }
                if (error > kTolerance * std::max(std::fabs(reference), 1.0)) {
                    if (mismatches == 0) {
                        std::printf("     %s: sample %llu component %u: gpu %.9g, cpu %.9g\n",
                                    label, static_cast<unsigned long long>(sample), c, actual,
                                    reference);
                    }
                    ++mismatches;
                }
            }
        }
        m_context.Readback().ReleaseOldest();

        std::printf("     %-22s %llu sample(s), %llu skipped, worst %.3g (scale %.3g)\n", label,
                    static_cast<unsigned long long>(samples),
                    static_cast<unsigned long long>(skipped), worst / scale, scale);
        CHECK_EQ(mismatches, u64_t{0});
        return mismatches == 0;
    }

private:
    [[nodiscard]] b8_t AddInput(Mapping mapping, SectionExtent extent, u32_t stream) {
        const u64_t         bytes = ValueSize(mapping, extent, kHalo);
        Result<SectionSlot> slot =
            m_context.Sections().Acquire(ClassOf(mapping, extent, kHalo), bytes);
        if (!slot) {
            std::printf("FAIL input slot: %s\n", slot.error().Format().data());
            return false;
        }

        Input& input   = m_inputs[m_inputCount++];
        input.mapping  = mapping;
        input.slot     = *slot;
        const u64_t elements = SampleCount(mapping, extent, kHalo) * mapping.components;
        input.host.resize(static_cast<usize_t>(elements));
        for (u64_t i = 0; i < elements; ++i) {
            input.host[static_cast<usize_t>(i)] = SampleValue(stream, i);
        }
        if (Status uploaded = test::UploadToSlot(m_context, input.slot, input.host.data(), bytes);
            !uploaded) {
            std::printf("FAIL input upload: %s\n", uploaded.error().Format().data());
            return false;
        }
        return true;
    }

    void ReleaseAll() {
        if (m_outputSlot.IsValid()) {
            m_context.Sections().Release(m_outputSlot);
        }
        for (usize_t i = m_inputCount; i-- > 0;) {
            if (m_inputs[i].slot.IsValid()) {
                m_context.Sections().Release(m_inputs[i].slot);
            }
            m_inputs[i].host.clear();
        }
        m_inputCount = 0;
    }

    Context&                           m_context;
    const Graph&                       m_graph;
    std::array<Input, kMaxNodeInputs>  m_inputs{};
    usize_t                            m_inputCount = 0;
    SectionSlot                        m_outputSlot;
};


/// CPU box blur, the reference for the neighbourhood op.
///
/// Written against the geometry of the input on purpose: the whole point of the check is that the
/// input carries a wider border than the output, so a kernel that reused the row stride of the
/// output would read the wrong samples and this would catch it.
void BoxBlurReference(const f32_t* input, f32_t* output, Domain domain, SectionExtent extent,
                      u32_t inputHalo, u32_t outputHalo, i32_t radius, u8_t components) {
    const auto padded = [&](u32_t halo) {
        const u32_t pad = 2 * halo;
        return std::array<u32_t, 3>{extent.x + pad, domain == Domain::R3 ? extent.y + pad : 1,
                                    extent.z + pad};
    };
    const std::array<u32_t, 3> nIn   = padded(inputHalo);
    const std::array<u32_t, 3> nOut  = padded(outputHalo);
    const i32_t                delta = static_cast<i32_t>(inputHalo - outputHalo);
    const i32_t                spanY = domain == Domain::R3 ? radius : 0;

    for (u32_t y = 0; y < nOut[1]; ++y) {
        for (u32_t z = 0; z < nOut[2]; ++z) {
            for (u32_t x = 0; x < nOut[0]; ++x) {
                const u64_t outAt = (static_cast<u64_t>(y) * nOut[2] + z) * nOut[0] + x;
                // The same world sample sits `delta` further in along every padded axis.
                const i32_t ix = static_cast<i32_t>(x) + delta;
                const i32_t iy = domain == Domain::R3 ? static_cast<i32_t>(y) + delta : 0;
                const i32_t iz = static_cast<i32_t>(z) + delta;

                for (u8_t c = 0; c < components; ++c) {
                    f64_t sum  = 0.0;
                    f64_t taps = 0.0;
                    for (i32_t dy = -spanY; dy <= spanY; ++dy) {
                        for (i32_t dz = -radius; dz <= radius; ++dz) {
                            for (i32_t dx = -radius; dx <= radius; ++dx) {
                                const i32_t tx = ix + dx;
                                const i32_t ty = iy + dy;
                                const i32_t tz = iz + dz;
                                if (tx < 0 || ty < 0 || tz < 0
                                    || tx >= static_cast<i32_t>(nIn[0])
                                    || ty >= static_cast<i32_t>(nIn[1])
                                    || tz >= static_cast<i32_t>(nIn[2])) {
                                    continue;
                                }
                                const u64_t inAt =
                                    (static_cast<u64_t>(ty) * nIn[2] + tz) * nIn[0] + tx;
                                sum += input[inAt * components + c];
                                taps += 1.0;
                            }
                        }
                    }
                    output[outAt * components + c] =
                        taps > 0.0 ? static_cast<f32_t>(sum / taps) : 0.0f;
                }
            }
        }
    }
}

/// Dispatches Blur with an input whose halo is wider than the one of the output, as halo propagation
/// would arrange it, and compares against the CPU box blur.
[[nodiscard]] b8_t CheckBlur(Context& context, Domain domain, i32_t radius, u8_t components,
                             u32_t outputHalo, const char* label) {
    const SectionExtent extent = domain == Domain::R3 ? kExtent3 : kExtent;
    const Mapping       mapping{domain, components};
    const u32_t         inputHalo = outputHalo + static_cast<u32_t>(radius);

    const u64_t inputSamples  = SampleCount(mapping, extent, inputHalo);
    const u64_t outputSamples = SampleCount(mapping, extent, outputHalo);
    const u64_t inputBytes    = ValueSize(mapping, extent, inputHalo);
    const u64_t outputBytes   = ValueSize(mapping, extent, outputHalo);

    Result<SectionSlot> inputSlot =
        context.Sections().Acquire(ClassOf(mapping, extent, inputHalo), inputBytes);
    if (!inputSlot) {
        std::printf("FAIL %s: %s\n", label, inputSlot.error().Format().data());
        return false;
    }
    Result<SectionSlot> outputSlot =
        context.Sections().Acquire(ClassOf(mapping, extent, outputHalo), outputBytes);
    if (!outputSlot) {
        context.Sections().Release(*inputSlot);
        std::printf("FAIL %s: %s\n", label, outputSlot.error().Format().data());
        return false;
    }

    std::pmr::vector<f32_t> host(static_cast<usize_t>(inputSamples * components),
                                 &memory::General().Resource());
    for (usize_t i = 0; i < host.size(); ++i) {
        host[i] = SampleValue(7, i);
    }

    b8_t ok = true;
    if (Status uploaded = test::UploadToSlot(context, *inputSlot, host.data(), inputBytes);
        !uploaded) {
        std::printf("FAIL %s: %s\n", label, uploaded.error().Format().data());
        ok = false;
    }

    if (ok) {
        Result<ComputePipeline> pipeline = ComputePipeline::Create(
            context.Device(), OpInfoOf(OpKind::Blur).shader,
            WorkgroupSpecialization(static_cast<u32_t>(domain)), context.Pipelines().Handle());
        if (!pipeline) {
            std::printf("FAIL %s: %s\n", label, pipeline.error().Format().data());
            ok = false;
        } else {
            KernelPushConstants constants{};
            constants.origin = {11, domain == Domain::R3 ? 5 : 0, -7};
            constants.extent = {extent.x, extent.y, extent.z};
            constants.halo   = outputHalo;
            constants.SetDomain(static_cast<u32_t>(domain));
            constants.SetChannelMask(1);
            constants.inputHalos = inputHalo & 0xFFu;
            constants.inputs[0]  = inputSlot->address;
            constants.outputs[0] = outputSlot->address;
            constants.params[0]  = static_cast<u32_t>(radius);
            constants.params[1]  = components;

            Result<test::Readback> readback =
                test::RunKernel(context, *pipeline, *outputSlot, constants, outputBytes);
            if (!readback) {
                std::printf("FAIL %s: %s\n", label, readback.error().Format().data());
                ok = false;
            } else {
                std::pmr::vector<f32_t> expected(
                    static_cast<usize_t>(outputSamples * components),
                    &memory::General().Resource());
                BoxBlurReference(host.data(), expected.data(), domain, extent, inputHalo,
                                 outputHalo, radius, components);

                u64_t mismatches = 0;
                f64_t worst      = 0.0;
                for (usize_t i = 0; i < expected.size(); ++i) {
                    const f64_t error = std::fabs(static_cast<f64_t>(readback->data[i])
                                                  - static_cast<f64_t>(expected[i]));
                    worst             = std::max(worst, error);
                    if (error > kTolerance) {
                        if (mismatches == 0) {
                            std::printf("     %s: sample %zu gpu %.9g cpu %.9g\n", label, i,
                                        static_cast<f64_t>(readback->data[i]),
                                        static_cast<f64_t>(expected[i]));
                        }
                        ++mismatches;
                    }
                }
                context.Readback().ReleaseOldest();
                std::printf("     %-22s radius %d, halos in %u out %u, %llu sample(s), worst %.3g\n",
                            label, radius, inputHalo, outputHalo,
                            static_cast<unsigned long long>(outputSamples), worst);
                CHECK_EQ(mismatches, u64_t{0});
                ok = mismatches == 0;
            }
        }
    }

    context.Sections().Release(*outputSlot);
    context.Sections().Release(*inputSlot);
    return ok;
}

[[nodiscard]] SourceLocation At(u32_t line) {
    return SourceLocation{.file = "test_kernels", .line = line};
}

} // namespace

int main() {
    const Result<Application*> application =
        engine::init(AppInfo{.mode = RunMode::Headless, .name = "test_kernels"});
    if (!application) {
        std::printf("FAIL engine::init: %s\n", application.error().Format().data());
        const Status closed = engine::shutdown(nullptr);
        (void)closed;
        return 1;
    }
    Context& context = VulkanContext(**application);

    const int result = [&]() -> int {
        // Placeholders only: the builders need a value of the right mapping to validate against, and
        // the checker substitutes its own slots at dispatch time.
        Graph graph;
        Result<Value> scalar =
            graph.AddConst(Mapping{Domain::R2, 1}, {0.0f, 0.0f, 0.0f, 0.0f}, At(1));
        REQUIRE_OK(scalar);
        Result<Value> vector2 =
            graph.AddConst(Mapping{Domain::R2, 2}, {0.0f, 0.0f, 0.0f, 0.0f}, At(2));
        REQUIRE_OK(vector2);
        Result<Value> vector3 =
            graph.AddConst(Mapping{Domain::R2, 3}, {0.0f, 0.0f, 0.0f, 0.0f}, At(3));
        REQUIRE_OK(vector3);
        Result<Value> scalar3 =
            graph.AddConst(Mapping{Domain::R3, 1}, {0.0f, 0.0f, 0.0f, 0.0f}, At(4));
        REQUIRE_OK(scalar3);

        OpChecker checker(context, graph);

        test::Section("Const");
        {
            Result<Value> node =
                graph.AddConst(Mapping{Domain::R2, 3}, {0.25f, -0.5f, 0.75f, 0.0f}, At(10));
            REQUIRE_OK(node);
            (void)checker.Check(node->node, "Const R2->R3");

            Result<Value> volume =
                graph.AddConst(Mapping{Domain::R3, 1}, {-0.125f, 0.0f, 0.0f, 0.0f}, At(11));
            REQUIRE_OK(volume);
            (void)checker.Check(volume->node, "Const R3->R1");
        }

        test::Section("Arith");
        {
            const ArithOp ops[] = {ArithOp::Add,     ArithOp::Subtract, ArithOp::Multiply,
                                   ArithOp::Divide,  ArithOp::Minimum,  ArithOp::Maximum};
            const char*   names[] = {"Add", "Subtract", "Multiply", "Divide", "Minimum", "Maximum"};
            for (usize_t i = 0; i < ArrayCount(ops); ++i) {
                Result<Value> node =
                    graph.AddArith(ops[i], *scalar, *scalar, At(static_cast<u32_t>(20 + i)));
                REQUIRE_OK(node);
                std::array<char, 32> label{};
                std::snprintf(label.data(), label.size(), "Arith %s", names[i]);
                (void)checker.Check(node->node, label.data(),
                                    ops[i] == ArithOp::Divide ? 1 : -1);
            }

            // Broadcasting, both ways round: an Rn->R1 operand must spread over an Rn->Rm one.
            Result<Value> broadcast = graph.AddArith(ArithOp::Multiply, *vector3, *scalar, At(30));
            REQUIRE_OK(broadcast);
            (void)checker.Check(broadcast->node, "Arith broadcast R3xR1");

            Result<Value> reversed = graph.AddArith(ArithOp::Add, *scalar, *vector2, At(31));
            REQUIRE_OK(reversed);
            (void)checker.Check(reversed->node, "Arith broadcast R1xR2");
        }

        test::Section("Curve");
        {
            Result<Value> clamp = graph.AddCurve(CurveOp::Clamp, *vector2, -0.3f, 0.6f, At(40));
            REQUIRE_OK(clamp);
            (void)checker.Check(clamp->node, "Curve Clamp");

            Result<Value> remap = graph.AddCurve(CurveOp::Remap, *scalar, -200.0f, 1800.0f, At(41));
            REQUIRE_OK(remap);
            (void)checker.Check(remap->node, "Curve Remap");

            Result<Value> power = graph.AddCurve(CurveOp::Power, *scalar, 2.5f, 0.0f, At(42));
            REQUIRE_OK(power);
            (void)checker.Check(power->node, "Curve Power");

            Result<Value> smooth =
                graph.AddCurve(CurveOp::Smoothstep, *vector3, -0.5f, 0.5f, At(43));
            REQUIRE_OK(smooth);
            (void)checker.Check(smooth->node, "Curve Smoothstep");
        }

        test::Section("Blend");
        {
            Result<Value> node = graph.AddBlend(*vector3, *vector3, *scalar, At(50));
            REQUIRE_OK(node);
            (void)checker.Check(node->node, "Blend R2->R3");

            Result<Value> scalarBlend = graph.AddBlend(*scalar, *scalar, *scalar, At(51));
            REQUIRE_OK(scalarBlend);
            (void)checker.Check(scalarBlend->node, "Blend R2->R1");
        }

        test::Section("Normals and SlopeMask");
        {
            Result<Value> normals = graph.AddNormals(*vector2, 1.0f, At(60));
            REQUIRE_OK(normals);
            (void)checker.Check(normals->node, "Normals");

            Result<Value> scaled = graph.AddNormals(*vector2, 4.0f, At(61));
            REQUIRE_OK(scaled);
            (void)checker.Check(scaled->node, "Normals scaled");

            Result<Value> mask = graph.AddSlopeMask(*vector2, 0.2f, 0.8f, At(62));
            REQUIRE_OK(mask);
            (void)checker.Check(mask->node, "SlopeMask");
        }

        test::Section("Vector");
        {
            for (u8_t component = 0; component < 3; ++component) {
                Result<Value> node = graph.AddExtract(*vector3, component,
                                                      At(static_cast<u32_t>(70 + component)));
                REQUIRE_OK(node);
                std::array<char, 32> label{};
                std::snprintf(label.data(), label.size(), "Vector Extract %u", component);
                (void)checker.Check(node->node, label.data());
            }

            const Value pair[2] = {*scalar, *scalar};
            Result<Value> combine2 = graph.AddCombine(pair, 2, At(80));
            REQUIRE_OK(combine2);
            (void)checker.Check(combine2->node, "Vector Combine 2");

            const Value triple[3] = {*scalar, *scalar, *scalar};
            Result<Value> combine3 = graph.AddCombine(triple, 3, At(81));
            REQUIRE_OK(combine3);
            (void)checker.Check(combine3->node, "Vector Combine 3");
        }

        test::Section("Blur, the neighbourhood op");
        {
            // Several radii and both domains, with a nonzero output halo so that the input and the
            // output genuinely differ in geometry rather than only in size.
            (void)CheckBlur(context, Domain::R2, 1, 1, 0, "Blur R2 r1");
            (void)CheckBlur(context, Domain::R2, 2, 1, 0, "Blur R2 r2");
            (void)CheckBlur(context, Domain::R2, 3, 2, 1, "Blur R2 r3 h1");
            (void)CheckBlur(context, Domain::R2, 1, 3, 2, "Blur R2 r1 h2");
            (void)CheckBlur(context, Domain::R3, 1, 1, 0, "Blur R3 r1");
            (void)CheckBlur(context, Domain::R3, 2, 1, 1, "Blur R3 r2 h1");
        }

        test::Section("R3 pointwise");
        {
            // The same ops over a volume, so the R3 workgroup shape and sample layout are exercised.
            Result<Value> sum = graph.AddArith(ArithOp::Add, *scalar3, *scalar3, At(90));
            REQUIRE_OK(sum);
            (void)checker.Check(sum->node, "Arith R3");

            Result<Value> curve = graph.AddCurve(CurveOp::Smoothstep, *scalar3, -0.4f, 0.4f, At(91));
            REQUIRE_OK(curve);
            (void)checker.Check(curve->node, "Curve R3");
        }

        return 0;
    }();

    CHECK_EQ(context.Sections().UsedBytes(), VkDeviceSize{0});

    if (const Status closed = engine::shutdown(*application); !closed) {
        std::printf("FAIL engine::shutdown: %s\n", closed.error().Format().data());
        return 1;
    }
    test::CheckNoValidationErrors();
    return result != 0 ? result : test::Summary("test_kernels");
}
